# Generated by Django 6.0.5 on 2026-05-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0004_product_category_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Still can buy'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
