# Generated by Django 6.0.5 on 2026-05-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0005_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
